s = set()
#print(type(s))
#s_from_list = set([1, 2, 3, 4])
#print(s_from_list)
s.add(1)
s.add(1)
s.add(2)
#print(s)
s.add(2)
s1 = s.union({1,5,9,6})
s2 = s.intersection({5, 7, 1})
s.remove(2)
#print(s, s1, s2)


