mystr = ("sajal is good")
#print(mystr[-1:0 ], end = "")
#print(len(mystr))
print(type(mystr))
print(mystr.endswith("is good"))
print(mystr.count("o"))
print(mystr.capitalize())
print(mystr.replace("is" , "are"))
print(mystr.center(20))